Exercises up to 214 are done, exercise 215 implemented partially. Tests for ex. 212-215 are waiting for implementation
vacho87/Exercises pull request #5
Opened 2020-11-07 00:06 UTC by vacho87

2020-11-13 09:00 UTC, alex-al-skiba requested changes

2020-11-13 09:00 UTC, alex-al-skiba commented on Exercises/DigitList.cs
> +
You're leaving a lot of empty lines here and there :)

2020-11-13 09:00 UTC, alex-al-skiba commented on Exercises/Exercise214.cs
> +        public static int AskForNumber()
Try to combine ExerciseChooser, NumberInput and this method into one helper.

2020-11-13 09:00 UTC, alex-al-skiba commented on Exercises/Exercise215.cs
> +        public static List<int> UseSimpleAddition(List<int> addend1Digits, List<int> addend2Digits)
Important note from the comment ("Use only(!) for addition of two not negative numbers") should be reflected in method name and ideally in parameter names.

2020-11-13 09:00 UTC, alex-al-skiba commented on Exercises/Exercise215.cs
> +        public static List<int> UseSimpleSubtraction(List<int> minuendDigits, List<int> subtrahendDigits)
Same as above, make method name more clear.

2020-11-13 09:00 UTC, alex-al-skiba commented on Exercises/Exercise215.cs
> +            if (list[0] > 0)
That can be a one-liner.

2020-11-13 09:00 UTC, alex-al-skiba commented on Exercises/Exercise215.cs
> +                return true;
General note: if you see an `if/else` statement and it only returns, that can be replaced with one-liner (using ternary operator or just returning the result of `if` condition).

2020-11-13 09:00 UTC, alex-al-skiba commented on Exercises/Exercise215.cs
> +            list1.Reverse();
Try using `Insert()` instead of reversing the list. that should be better both for readability and performance.

2020-11-13 09:00 UTC, alex-al-skiba commented on Exercises/Exercise22.cs
> +            foreach (char symbol in list) Console.Write($" {symbol},");
please avoid one-liners that should be enclosed in curly brackets (AV1535 in coding guidelines)

2020-11-13 21:05 UTC, vacho87 commented on Exercises/DigitList.cs
> +
> You're leaving a lot of empty lines here and there :)

It was raw, uncompleted class for Ex216

2020-11-13 22:09 UTC, vacho87 commented on Exercises/Exercise22.cs
> +            foreach (char symbol in list) Console.Write($" {symbol},");
> please avoid one-liners that should be enclosed in curly brackets (AV1535 in coding guidelines)

Can't understand what do your mean.
In addition here is suggestion by number AV1535 in coding guidelines: "Always add a block after the keywords `if`, `else`, `do`, `while`, `for`, `foreach` and `case` (AV1535)"

2020-11-14 20:47 UTC, vacho87 commented
All of the suggestions are implemented

2020-11-16 09:00 UTC, alex-al-skiba commented on Exercises/ServiceClass.cs
> +        public static int AskChoice ()
let's combine those methods together

2020-12-21 05:23 UTC, merged